CREATE TABLE `ledger_entries` (
    `ENTRY_ID` VARCHAR(36) PRIMARY KEY,
    `IDEMPOTENCY_KEY` VARCHAR(255) NOT NULL,
    `TRANSACTION_TYPE` VARCHAR(30) NOT NULL,
    `TRANSACTION_ID` VARCHAR(255) NOT NULL,
    `ORDER_ID` VARCHAR(255),
    `USER_ID` VARCHAR(255),
    `ACCOUNT_ID` VARCHAR(255) NOT NULL,
    `AMOUNT` DECIMAL(19, 2) NOT NULL,
    `CURRENCY` VARCHAR(3) NOT NULL,
    `DIRECTION` VARCHAR(10) NOT NULL,
    `STATUS` VARCHAR(20) NOT NULL,
    `DESCRIPTION` VARCHAR(1000),
    `CREATED_AT` TIMESTAMP NOT NULL,
    `REVERSED_ENTRY_ID` VARCHAR(36),
    `VERSION` BIGINT,
    CONSTRAINT `UK_LEDGER_ENTRIES_IDEMPOTENCY_KEY` UNIQUE (`IDEMPOTENCY_KEY`)
);
